"""Generate GAIT's opt-in action family without rewriting native move classes.

Run without arguments from the source package to update its graph.  --check
checks for generator drift without writing.  --output selects another target.
"""

from argparse import ArgumentParser
from pathlib import Path


DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "addons/gait/slope_actions.hpp"
)
FAMILIES = (
    ("SrasWrfl", "GAIT_SlopeRifleRaisedActions", "RifleStandActions"),
    ("SlowWrfl", "GAIT_SlopeRifleLoweredActions", "RifleLowStandActions"),
    ("SrasWpst", "GAIT_SlopePistolActions", "PistolStandActions"),
    ("SnonWnon", "GAIT_SlopeUnarmedActions", "CivilStandActions"),
)
DIRECTIONS = ("Df", "Dfl", "Dl", "Dbl", "Db", "Dbr", "Dr", "Dfr")
SELECTORS = ("F", "LF", "L", "LB", "B", "RB", "R", "RF")
FORWARD = {"Df", "Dfl", "Dfr"}
PACES = (
    "Walk", "PlayerWalk", "Slow", "PlayerSlow",
    "Fast", "PlayerFast", "Tact", "PlayerTact",
)
IDLE_SELECTORS = (
    "Default", "Stop", "StopRelaxed", "TurnL", "TurnR",
    "TurnLRelaxed", "TurnRRelaxed",
)


def native(family, direction, brace=False):
    if direction == "Dnon":
        pace = "Mstp"
    else:
        pace = "Mwlk" if brace else "Meva" if direction in FORWARD else "Mrun"
    return f"AmovPerc{pace}{family}{direction}"


def custom(family, direction, brace=False):
    suffix = "Brace" if brace and direction == "Dnon" else ""
    return native(family, direction, brace) + suffix + "_GAIT"


def action_name(actions, brace):
    return actions.replace("Actions", "BraceActions") if brace else actions


def ordinary_states(family):
    """Existing entry/release endpoints, not destinations for held-sprint input.

    Keep the RC3 native walk/run/sprint endpoints.  The lowered-rifle variant
    names also occur in ACE's movement config.  Do not guess unarmed/pistol
    tactical variants, special turn clips, or injury transitions.
    """
    states = [native(family, "Dnon")]
    states += [
        f"AmovPerc{pace}{family}{direction}"
        for pace in ("Mrun", "Mwlk") for direction in DIRECTIONS
    ]
    states += [native(family, direction) for direction in DIRECTIONS if direction in FORWARD]
    if family == "SlowWrfl":
        states += [
            f"AmovPerc{pace}{family}{direction}_ver2"
            for pace in ("Mwlk", "Mtac") for direction in DIRECTIONS
        ]
    return states


def append_edges(lines, field, names):
    if len(names) != len(set(names)):
        raise ValueError(f"Duplicate generated {field} endpoint")
    lines.extend([f"            {field}[] +=", "            {"])
    for index, name in enumerate(names):
        weight = "0.025" if "Meva" in name else "0.02"
        comma = "," if index < len(names) - 1 else ""
        lines.append(f'                "{name}", {weight}{comma}')
    lines.append("            };")


def render():
    lines = ['''/*
 * GAIT 1.8 foundation: opt-in standing locomotion action families.
 * Generated by tools/generate_foundation_actions.py; edit the generator.
 *
 * Each weapon family contains one native-pose idle, three real Meva sprint
 * clips, and five Mrun lateral/backward clips. Each also has a brief brace
 * family using eight actual Mwlk clips and a separate native-pose idle.
 * Only a genuine low-momentum brace uses those states; one handoff advances
 * to the original sprint family when the tuned brace window ends.
 * The controller enters once;
 * native directional input chooses transitions inside the selected family.
 * Default, Stop and StopRelaxed remain inside that family. Turn selectors use
 * its idle as a conservative fallback: no guessed native turn class is used.
 * The engine still controls orientation; in-place foot turning needs testing.
 *
 * All ordinary pace selectors point to custom movement states, including Walk
 * requests on slopes. This is an intended state-selection policy, not proof
 * that the engine permits sprint root motion on every terrain inclination.
 *
 * Preserve the inherited Actions destinations for stance, weapon, injury,
 * medical, vault and vehicle actions. Preserve native transition arrays too:
 * overwriting them from an incomplete config dump would discard valid exits
 * added by the game or ACE. Complete direct custom routes are appended;
 * inherited native routes remain available for actions and controlled release.
 * This is NOT a claim that all inherited native locomotion edges are removed.
 *
 * Custom-state variants are empty to avoid automatic native idle/fidget
 * variants leaving the family. No ConnectTo self-loop is forced. Animation
 * files, speed, duty, collision and other pose properties inherit unchanged.
 * Transition weights are graph costs, not fixed blend durations in seconds.
 *
 * Sources for native names/selectors and preserving explicit action exits:
 * https://community.bistudio.com/wiki/Arma_3:_Moves
 * https://github.com/acemod/ACE3/blob/master/addons/dragging/CfgMovesBasic.hpp
 * https://github.com/acemod/ACE3/blob/master/addons/movement/CfgMoves.hpp
 */
class CfgMovesBasic
{
    class Actions
    {''']
    for family, actions, parent in FAMILIES:
        lines.append(f"        class {parent};")
        for brace in (False, True):
            lines += [f"        class {action_name(actions, brace)}: {parent}", "        {"]
            lines.append("            // Keep default/stop/turn selection in this opt-in family.")
            for selector in IDLE_SELECTORS:
                lines.append(f'            {selector} = "{custom(family, "Dnon", brace)}";')
            for pace in PACES:
                for selector, direction in zip(SELECTORS, DIRECTIONS):
                    lines.append(f'            {pace}{selector} = "{custom(family, direction, brace)}";')
            lines += ["        };", ""]
    lines += ["    };", "};", "", "class CfgMovesMaleSdr: CfgMovesBasic", "{", "    class States", "    {"]
    for family, actions, _ in FAMILIES:
        directions = ("Dnon", *DIRECTIONS)
        bases = dict.fromkeys(native(family, direction, brace) for brace in (False, True) for direction in directions)
        for base in bases:
            lines.append(f"        class {base};")
        lines.append("")
        ordinary = ordinary_states(family)
        for brace in (False, True):
            members = [custom(family, other, brace) for other in directions]
            for direction in directions:
                name = custom(family, direction, brace)
                base = native(family, direction, brace)
                role = "brace" if brace else "idle" if direction == "Dnon" else "move"
                lines += [
                    f"        class {name}: {base}", "        {",
                    f'            actions = "{action_name(actions, brace)}";',
                    "            GAIT_slopeState = 1;",
                    f'            GAIT_nativeState = "{base}";',
                    f'            GAIT_slopeFamily = "{family}";',
                    f'            GAIT_locomotionRole = "{role}";',
                    "            looped = 1;",
                    "            equivalentTo = \"\";",
                    "            variantsPlayer[] = {};",
                    "            variantsAI[] = {};",
                    "            // Native entry endpoints also support graph-based diagnostics.",
                ]
                append_edges(lines, "InterpolateFrom", ordinary)
                lines.append("            // Keep each pace stage complete; the controller promotes brace once.")
                internal = [other for other in members if other != name]
                # Brace may promote to any live sprint direction. The original
                # sprint graph must never route back into brace by itself.
                if brace:
                    internal += [custom(family, other) for other in directions]
                append_edges(lines, "InterpolateTo", internal + ordinary)
                lines += ["        };", ""]
    lines += ["    };", "};", ""]
    return "\n".join(lines)


def main():
    parser = ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if args.output.read_text() != expected:
            raise SystemExit(f"Generated config differs: {args.output}")
        print("Foundation graph generator matches the checked-in config.")
        return
    args.output.write_text(expected)
    print(f"Wrote {args.output}: 72 states, 8 action families, 568 mapped selectors.")


if __name__ == "__main__":
    main()
