"""Generate GAIT's opt-in action family without rewriting native move classes.

Run without arguments from the source package to update its graph.  --check
checks for generator drift without writing.  --output selects another target.
"""

from argparse import ArgumentParser
from pathlib import Path


DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "addons/gait/slope_actions.hpp"
)
FAMILIES = (
    ("SrasWrfl", "GAIT_SlopeRifleRaisedActions", "RifleStandActions"),
    ("SlowWrfl", "GAIT_SlopeRifleLoweredActions", "RifleLowStandActions"),
    ("SrasWpst", "GAIT_SlopePistolActions", "PistolStandActions"),
    ("SnonWnon", "GAIT_SlopeUnarmedActions", "CivilStandActions"),
)
DIRECTIONS = ("Df", "Dfl", "Dl", "Dbl", "Db", "Dbr", "Dr", "Dfr")
SELECTORS = ("F", "LF", "L", "LB", "B", "RB", "R", "RF")
FORWARD = {"Df", "Dfl", "Dfr"}
PACES = (
    "Walk", "PlayerWalk", "Slow", "PlayerSlow",
    "Fast", "PlayerFast", "Tact", "PlayerTact",
)
IDLE_SELECTORS = (
    "Default", "Stop", "StopRelaxed", "TurnL", "TurnR",
    "TurnLRelaxed", "TurnRRelaxed",
)


def native(family, direction, sprinting=True):
    if direction == "Dnon":
        pace = "Mstp"
    else:
        pace = "Meva" if sprinting and direction in FORWARD else "Mrun"
    return f"AmovPerc{pace}{family}{direction}"


def custom(family, direction, sprinting=True):
    return native(family, direction, sprinting) + "_GAIT"


def stop_target(family):
    return native(family, "Dnon") + "_GAITStop"


def ordinary_states(family):
    """Existing entry/release endpoints, not destinations for held-sprint input.

    Keep the RC3 native walk/run/sprint endpoints.  The lowered-rifle variant
    names also occur in ACE's movement config.  Lowered pistol movement feeds
    the same pistol sprint family; omitting it causes a native detour on entry.
    Do not add unarmed/pistol tactical variants or special action transitions.
    """
    states = [native(family, "Dnon")]
    states += [
        f"AmovPerc{pace}{family}{direction}"
        for pace in ("Mrun", "Mwlk") for direction in DIRECTIONS
    ]
    states += [native(family, direction) for direction in DIRECTIONS if direction in FORWARD]
    if family == "SlowWrfl":
        states += [
            f"AmovPerc{pace}{family}{direction}_ver2"
            for pace in ("Mwlk", "Mtac") for direction in DIRECTIONS
        ]
    if family == "SrasWpst":
        states += ["AmovPercMstpSlowWpstDnon"]
        states += [
            f"AmovPerc{pace}SlowWpst{direction}"
            for pace in ("Mrun", "Mwlk") for direction in DIRECTIONS
        ]
        states += [f"AmovPercMevaSlowWpst{direction}" for direction in DIRECTIONS if direction in FORWARD]
    return states


def append_edges(lines, field, names):
    if len(names) != len(set(names)):
        raise ValueError(f"Duplicate generated {field} endpoint")
    lines.extend([f"            {field}[] +=", "            {"])
    for index, name in enumerate(names):
        weight = "0.025" if "Meva" in name else "0.02"
        comma = "," if index < len(names) - 1 else ""
        lines.append(f'                "{name}", {weight}{comma}')
    lines.append("            };")


def render():
    lines = ['''/*
 * GAIT 1.8 foundation: opt-in standing locomotion action families.
 * Generated by tools/generate_foundation_actions.py; edit the generator.
 *
 * Each weapon family contains one native-pose idle, three real Meva sprint
 * clips, and eight Mrun jog/directional clips. Ordinary slope movement uses
 * Mrun even when the engine requests Walk/Slow; the original numerical brace
 * acts inside this family from the first run frame. There is no separate
 * walking stage or promotion request. playMoveNow enters/releases through
 * the explicit interpolation graph once;
 * native directional input chooses transitions inside the selected family.
 * Default, Stop and StopRelaxed remain inside that family. Turn selectors use
 * its idle as a conservative fallback: no guessed native turn class is used.
 * The engine still controls orientation; in-place foot turning needs testing.
 *
 * All ordinary pace selectors point to custom movement states, including Walk
 * requests on slopes. This is an intended state-selection policy, not proof
 * that the engine permits sprint root motion on every terrain inclination.
 *
 * Preserve the inherited Actions destinations for stance, weapon, injury,
 * medical, vault and vehicle actions. Preserve native transition arrays too:
 * overwriting them from an incomplete config dump would discard valid exits
 * added by the game or ACE. Complete direct custom routes are appended;
 * inherited native routes remain available for actions and controlled release.
 * This is NOT a claim that all inherited native locomotion edges are removed.
 *
 * Custom-state variants are empty to avoid automatic native idle/fidget
 * variants leaving the family. No ConnectTo self-loop is forced. Animation
 * files, speed, duty, collision and other pose properties inherit unchanged.
 * Four native-action stop targets double idle interpolationSpeed from the
 * captured native value 4 to 8. They shorten the outgoing run blend without
 * scaling its clip playback or adding forward movement. They do not belong
 * to the sprint family and accept new movement immediately through native
 * actions. In-game distance reduction still depends on engine blending.
 * Transition weights are graph costs, not fixed blend durations in seconds.
 *
 * Sources for native names/selectors and preserving explicit action exits:
 * https://community.bistudio.com/wiki/Arma_3:_Moves
 * https://github.com/acemod/ACE3/blob/master/addons/dragging/CfgMovesBasic.hpp
 * https://github.com/acemod/ACE3/blob/master/addons/movement/CfgMoves.hpp
 */
class CfgMovesBasic
{
    class Actions
    {''']
    for family, actions, parent in FAMILIES:
        lines.append(f"        class {parent};")
        lines += [f"        class {actions}: {parent}", "        {"]
        lines.append("            // Keep default/stop/turn selection in this opt-in family.")
        for selector in IDLE_SELECTORS:
            lines.append(f'            {selector} = "{custom(family, "Dnon")}";')
        for pace in PACES:
            sprinting = pace in ("Fast", "PlayerFast")
            for selector, direction in zip(SELECTORS, DIRECTIONS):
                lines.append(f'            {pace}{selector} = "{custom(family, direction, sprinting)}";')
        lines += ["        };", ""]
    lines += ["    };", "};", "", "class CfgMovesMaleSdr: CfgMovesBasic", "{", "    class States", "    {"]
    for family, actions, native_actions in FAMILIES:
        state_specs = [("Dnon", False)]
        state_specs += [(direction, True) for direction in DIRECTIONS if direction in FORWARD]
        state_specs += [(direction, False) for direction in DIRECTIONS]
        declarations = []
        for direction, sprinting in state_specs:
            base = native(family, direction, sprinting)
            if base not in declarations:
                declarations.append(base)
                lines.append(f"        class {base};")
        lines.append("")
        ordinary = ordinary_states(family) + [stop_target(family)]
        members = [custom(family, direction, sprinting) for direction, sprinting in state_specs]
        for direction, sprinting in state_specs:
            name = custom(family, direction, sprinting)
            base = native(family, direction, sprinting)
            role = "idle" if direction == "Dnon" else "move"
            lines += [
                f"        class {name}: {base}", "        {",
                f'            actions = "{actions}";',
                "            GAIT_slopeState = 1;",
                f'            GAIT_nativeState = "{base}";',
                f'            GAIT_slopeFamily = "{family}";',
                f'            GAIT_locomotionRole = "{role}";',
                "            looped = 1;",
                "            equivalentTo = \"\";",
                "            variantsPlayer[] = {};",
                "            variantsAI[] = {};",
                "            // Explicit graph routes let playMoveNow interpolate entry and release.",
            ]
            append_edges(lines, "InterpolateFrom", ordinary)
            lines.append("            // Complete direct idle/direction routes preserve the slope family.")
            internal = [other for other in members if other != name]
            append_edges(lines, "InterpolateTo", internal + ordinary)
            lines += ["        };", ""]
        # A separate native-pose endpoint confines the faster blend to stops.
        # Changing sprint interpolationSpeed would also change launch/retaps.
        lines += [
            f"        class {stop_target(family)}: {native(family, 'Dnon')}", "        {",
            f'            actions = "{native_actions}";',
            "            interpolationSpeed = 8;",
            "            equivalentTo = \"\";",
            "            variantsPlayer[] = {};",
            "            variantsAI[] = {};",
        ]
        append_edges(lines, "InterpolateFrom", members + ordinary_states(family))
        append_edges(lines, "InterpolateTo", members + ordinary_states(family))
        lines += ["        };", ""]
    lines += ["    };", "};", ""]
    return "\n".join(lines)


def main():
    parser = ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if args.output.read_text() != expected:
            raise SystemExit(f"Generated config differs: {args.output}")
        print("Foundation graph generator matches the checked-in config.")
        return
    args.output.write_text(expected)
    print(f"Wrote {args.output}: 48 locomotion states, 4 stop targets, 4 action families, 284 mapped selectors.")


if __name__ == "__main__":
    main()
